CREATE TABLE IF NOT EXISTS Diary
(
    id      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    note    text,
    date    date,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);