CREATE TABLE IF NOT EXISTS weather_history
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp     int,
    lastname varchar,
    date     date,
    city     varchar
);

CREATE TABLE IF NOT EXISTS previous_step
(
    user_id   bigint PRIMARY KEY,
    previous_step text,
    previous_id int
);

