CREATE TABLE IF NOT EXISTS weather_history
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp     int,
    date     date,
    city     varchar
);

CREATE TABLE IF NOT EXISTS previous_step
(
    user_id       bigint PRIMARY KEY,
    previous_step varchar,
    next_step     varchar,
    data          varchar,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

