CREATE TABLE IF NOT EXISTS users
(
    id            bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    firstname     varchar,
    lastname      varchar,
    registered_at timestamp,
    username      varchar
);

CREATE TABLE IF NOT EXISTS weather_history
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temp     int,
    lastname varchar,
    date     date,
    city     varchar
);

CREATE TABLE IF NOT EXISTS Diary
(
    id      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    note    text,
    date    date
);

CREATE TABLE IF NOT EXISTS previous_step
(
    user_id   bigint PRIMARY KEY,
    previous_step text
);

